global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: [Alertname]
  receiver: 
    - email-me
    - slack-notifications

receivers:
- name: email-me
  email_configs:
  - to: ahmed.a.elgebaly.95@gmail.com
    from: uadacity.fwd@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: uadacity.fwd@gmail.com
    auth_identity: uadacity.fwd@gmail.com
    auth_password: bxdrhibcyqosvrpq
    send_resolved: true

- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-instances'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}