global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'prometheus'

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    ec2_sd_configs:
      - region: us-west-2
        port: 9100
        filters:
          - name: tag:Project
            values: [Udapeople]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Project, __meta_ec2_tag_Name]
        separator: "_"
        target_label: instance
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: public_dns_name
  - job_name: 'alertmanager'
    ec2_sd_configs:
      - region: us-west-2
        port: 9093
        filters:
          - name: tag:Monitoring
            values: [Prometheus]
  - job_name: 'node_exporter'
    ec2_sd_configs:
      - region: us-west-2
        port: 9090
        filters:
          - name: tag:Monitoring
            values: [Prometheus]