groups:
- name: Down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 3m
    labels:
      severity: 'CRITICAL'
    annotations:
      summary: "Instance {{ $labels.instance }} is down"
      description: " Server {{ $labels.instance }} is Down"

- name: HostOutOfMemory
  rules:
  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 30
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory is filling up (< 30% left)\n Instance = {{ $labels.instance }}\n Public DNS =  {{ $labels.public_dns_name }}"

- name: HighLoad
  rules:
  - alert: high_load
    expr: node_load1 > 0.5
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} is under high load.'
      summary: Instance {{ $labels.instance }} under high load
      value: '{{ $value }}'
